version: '3'
services:
#   notes-client:
#     build:
#       context: ./notes-client/notesapp
#       dockerfile: Dockerfile
#     depends_on: 
#       - notes-service
#     restart: always
#     container_name: notes-client
#     ports:
#       - 40001:40001
#     network_mode: host
# #     hostname: localhost

  notes-service:
    build:
      context: ./notes
      dockerfile: Dockerfile
    depends_on:
      - notesdb
    restart: always
    environment:
      - mysql_username=myuser
      - mysql_password=password
      - mysql_dbname=ccassignment
    container_name: notes-service
    links:
      - notesdb
    ports:
      - 40002:40002
#     network_mode: host
#     hostname: localhost


  notesdb:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_USER=myuser
      - MYSQL_DATABASE=ccassignment
    container_name: notesdb
    ports:
      - 40003:40003
#     network_mode: host
#     hostname: localhost
